name: Build-OpenWrt

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 0 16 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    #    timeout-minutes: 360

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Init Compilation Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh | sudo bash

      - name: Clone Source
        run: |
          cd /home/runner
          bash ${GITHUB_WORKSPACE}/clone_source.sh
          sudo chown -R runner:runner immortalwrt

      - name: Before Build
        run: |
          bash ${GITHUB_WORKSPACE}/before_build.sh
          cp -fpR ${GITHUB_WORKSPACE}/. /home/runner/immortalwrt/

      - name: Start Build
        run: |
          cd /home/runner/immortalwrt
          rm -f .config*
          cp ${GITHUB_WORKSPACE}/.config /home/runner/immortalwrt
          make defconfig
          cat .config
          make -j$[$(nproc)+1] || make -j1 V=sc

      - name: After Build
        run: |
          bash /home/runner/immortalwrt/after_build.sh

      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: /home/runner/immortalwrt/bin/packages/

      - name: Upload Firmwares
        uses: actions/upload-artifact@v2
        with:
          name: Firmwares
          path: /home/runner/immortalwrt/bin/targets/
